services:
  faq-bot-php:
    container_name: faq-bot-app
    build:
      dockerfile: inf/php.Dockerfile
    volumes:
      - .:/var/www

  faq-bot-horizon:
    container_name: faq-bot-horizon
    build:
      dockerfile: inf/horizon.Dockerfile
    volumes:
      - .:/var/www
    entrypoint: php artisan horizon

  faq-bot-nginx:
    container_name: faq-bot-nginx
    image: nginx:latest
    volumes:
      - ./inf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
      - ./inf/ssl/server.crt:/etc/nginx/certs/server.crt
      - ./inf/ssl/server.key:/etc/nginx/certs/server.key
    ports:
      - "80:80"
      - "443:443"

  faq-bot-db:
    container_name: faq-bot-db
    image: postgres:14.1-alpine
    env_file: .env
    volumes:
      - pgdata:/var/lib/post-bot-db/data
    ports:
      - "5439:5432"

  faq-bot-redis:
    container_name: faq-bot-redis
    restart: always
    image: redis:latest
    ports:
      - "6378:6379"

volumes:
  pgdata:
